name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:  # yamllint disable-line rule:truthy
  pull_request:
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN_FOR_PREVIEWS }}
      - name: Download Reference Doc
        run:  |
          curl https://codeload.github.com/ClickHouse/ClickHouse/tar.gz/master | tar -xz -C ./ --strip=2 "ClickHouse-master/docs/"
          cp -R ./en docs
          cp -R ./ru docs/
          cp -R ./zh docs/
      - name: Build Project Artifacts
        run:  |
          export NODE_OPTIONS="--max_old_space_size=4096"
          vercel build --token=${{ secrets.VERCEL_TOKEN_FOR_PREVIEWS }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_FOR_PREVIEWS }}
      - name: Get Vercel Preview URL
        id: get-vercel-preview-url
        uses: ViktorJT/Get-vercel-preview-url@1.2.2
        with:
          vercel_access_token: ${{ secrets.VERCEL_TOKEN_FOR_PREVIEWS }}
          vercel_team_id: ${{ secrets.VERCEL_ORG_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo preview
        run: echo "Preview url is ready ${{ steps.get-vercel-preview-url.outputs.preview_url }}"
